# -*- coding: utf-8 -*-
"""Lichess_Data_Analysis (3).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dez4sojQHhV5drQeQ2aJHmOeaUIUqwvv
"""

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

#install external libs
!pip install seaborn

# Commented out IPython magic to ensure Python compatibility.
import math
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

lichess_data = pd.read_csv('/kaggle/input/chess/games.csv')
lichess_data.head()

lichess_data.info()

lichess_data.isnull().sum()

sns.countplot(x="victory_status",data=lichess_data)

sns.countplot(x="turns",data=lichess_data)

sns.countplot(x="opening_ply",data=lichess_data)

lichess_data["turns"].plot.hist()

lichess_data["white_rating"].plot.hist()

sns.boxplot(x="victory_status",y="turns",data=lichess_data)

sns.boxplot(x="victory_status",y="white_rating",data=lichess_data)

sns.boxplot(x="victory_status",y="black_rating",data=lichess_data)

sns.scatterplot(x="white_rating",y="black_rating",data=lichess_data)

sns.lineplot(x="white_rating",y="black_rating",data=lichess_data)

sns.boxenplot(x="opening_eco", y="turns",
              scale="linear", data=lichess_data)

sns.jointplot("white_rating", "black_rating", kind='reg',data=lichess_data,
                  height=7)